---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - scaling.scaling.com
  resources:
  - synthenticmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.scaling.com
  resources:
  - synthenticmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.scaling.com
  resources:
  - synthenticmetrics/status
  verbs:
  - get
  - patch
  - update
