# permissions for end users to edit synthenticmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/managed-by: kustomize
  name: synthenticmetric-editor-role
rules:
- apiGroups:
  - scaling.scaling.com
  resources:
  - synthenticmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.scaling.com
  resources:
  - synthenticmetrics/status
  verbs:
  - get
