apiVersion: scaling.scaling.com/v1alpha1
kind: SynthenticMetric
metadata:
  labels:
    app.kubernetes.io/name: my-app-synthetic-metric
    app.kubernetes.io/managed-by: kustomize
  name: synthenticmetric-sample-deployment
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "my-sample-app" # Name of the deployment to target
  metrics:
    - weight: 70
      type: Pods
      pods:
        metric:
          name: "cpu_usage_rate" # Example custom metric name for CPU usage
        target:
          type: AverageValue
          averageValue: "60" # Target 60% CPU utilization (represented as a whole number if the metric is in %)
                             # Or target 60m if the metric is cpu cores (e.g. milli-cores)
                             # Ensure this unit matches what your metric server provides for 'cpu_usage_rate'
    - weight: 30
      type: Pods
      pods:
        metric:
          name: "memory_usage_gb" # Example custom metric name for Memory GB usage
        target:
          type: AverageValue
          averageValue: "2" # Target 2GB memory usage
                             # Ensure this unit matches what your metric server provides for 'memory_usage_gb'
